apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: tutti
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80 # 클러스터 내부 호출 포트 (Cloudflared가 여기로)
      targetPort: 3000 # 컨테이너 내 Next.js 포트
      protocol: TCP
      name: http
