apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tutti

resources:
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/hpa.yaml

labels:
  - pairs:
      project: tutti-platform
